-
        name: Sprawdzenie polaczenia
        hosts: all
        tasks:
         - name: 'wykonanie data'
           command: echo date
         - name: 'display resolv.conf'
           command: cat /etc/resolv.conf
           register: result

         - name: print resolve.conf
           debug: var=result.stdout


         - name: "Display hostname"
           debug:
             var=ansible_hostname

         - name: "Display anoter hostname"
           debug:
             msg:
             - "ansible_distribution {{ hostvars[inventory_hostname].ansible_distribution }}"
             - "major version {{ hostvars[inventory_hostname].ansible_distribution_major_version }}"
             - "version {{ hostvars[inventory_hostname].ansible_distribution_version }}"
         - name: "Display anoter1"
           debug:
             msg: "{{ hostvars[inventory_hostname].ansible_distribution }}"
         - name: "Display anoter2"
           debug:
             msg: "{{ hostvars[inventory_hostname].ansible_distribution_major_version }}"
         - name: "Display anoter3"
           debug:
             msg: "{{ hostvars[inventory_hostname].ansible_distribution_version }}"

         - name: obtain OS version
           shell: Redhat-release
           register: result

         - name: print OS version
           debug: var=result.stdout
